/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GroupView {
  'id' : string,
  'name' : string,
  'memberCount' : bigint,
  'description' : string,
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'senderUsername' : string,
  'groupId' : string,
  'timestamp' : Time,
  'senderId' : Principal,
}
export interface PublicUserProfile {
  'username' : string,
  'email' : string,
  'lastSeen' : Time,
  'online' : boolean,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, string, string], undefined>,
  'getAllGroups' : ActorMethod<[], Array<GroupView>>,
  'getAllUsers' : ActorMethod<[], Array<PublicUserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PublicUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroup' : ActorMethod<[string], GroupView>,
  'getMessages' : ActorMethod<[string, [] | [Time]], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], bigint>,
  'validateSessionToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];