/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GroupView = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const PublicUserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'lastSeen' : Time,
  'online' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'senderUsername' : IDL.Text,
  'groupId' : IDL.Text,
  'timestamp' : Time,
  'senderId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllGroups' : IDL.Func([], [IDL.Vec(GroupView)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(PublicUserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([IDL.Text], [GroupView], []),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Opt(Time)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'validateSessionToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GroupView = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const PublicUserProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'lastSeen' : Time,
    'online' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'senderUsername' : IDL.Text,
    'groupId' : IDL.Text,
    'timestamp' : Time,
    'senderId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllGroups' : IDL.Func([], [IDL.Vec(GroupView)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(PublicUserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([IDL.Text], [GroupView], []),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Opt(Time)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'validateSessionToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };